### ISSUE TITLE
How do I append new data into existing timeline?

### ISSUE THREAD

**Issue by datnguyen0606** [Albejr/jquery-albe-timeline#11]
I'd like to append data to an existing timeline instead of loading all data again.
Thanks in advance.

**Comment by Albejr** [comment]
The library does not work as "Observable", so I think about improving it there in the future.

Sample:
[https://stackblitz.com/edit/jquery-albe-timeline](https://stackblitz.com/edit/jquery-albe-timeline?file=index.html)
