### ISSUE TITLE
<p> tag 

### ISSUE THREAD

**Issue by maeverson** [Albejr/jquery-albe-timeline#13]
Hi, 

I'm working with Albe Timeline plugin and I realized that are a issue with <p> tags. Depending on length of the string that will appear in <p> tag, the css breaks the element <p>.

In examples, if the string haves 170 chars, it will shows normally. Less than 170 char, the issue appears.
 
How to fix this ?

![captura de tela 2018-05-22 as 09 40 07](https://user-images.githubusercontent.com/7434091/40363070-c4f8b654-5da4-11e8-88a1-0ff1e721fa82.png)

**Comment by Albejr** [comment]
Fixed. 
Style property was missing for the panel.

`
section#timeline > article > div.panel { width: 100%; }
`

Update your css file like:
https://github.com/Albejr/jquery-albe-timeline/blob/master/templates/audain/style-albe-timeline.css

**Comment by maeverson** [comment]
Thaks !!!
