### ISSUE TITLE
French

### ISSUE THREAD

**Issue by cavo789** [Albejr/jquery-albe-timeline#3]
Hello

Here is my small contribution for French translation

```javascsript
	"fr-FR": {
		monthNames: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
		dayNames: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
		msgEmptyContent: "Aucune information à afficher."
	},
```

Can be use for fr-FR, fr-CA, fr-BE, ... Perhaps should you also check on the three first positions ("en", "fr", ...) and not on the five...

**Comment by Albejr** [comment]
the same for all locations ?

fr-BE	Belgium
fr-CA	Canada
fr-FR	France
fr-LU	Luxembourg
fr-MC	Monaco
fr-CH	Switzerland

**Comment by cavo789** [comment]
For these strings, yes.

It's like your en-US : will also works for en-GB ;-)

So, perhaps, code something like "If I don't match pt-BR or pt-PT, check if there is something for just 'pt'"; just a suggestion ;-)

**Comment by Albejr** [comment]
Check new version (2.0.0)
Override the default language.

The public variable "$.fn.albeTimeline.languages" allows you to specify multiple languages ​​in the timeline.

**Comment by Albejr** [comment]
jQuery(document).ready(function () {
    
    //New CutureInfo
    $.fn.albeTimeline.languages = [{
        "fr-FR": {
            days: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
            months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
            shortMonths: ["Jan","Fév","Mar","Avr","Mai","Juin", "Juil","Août","Sep","Oct","Nov","Déc"],
            msgEmptyContent: "Aucune information à afficher."
        }
    }];
    
    $("#myTimeline").albeTimeline(data, {
        language: "fr-FR",  //Default: pt-BR
    });

});

**Comment by cavo789** [comment]
It's working 👍 

No need to hack your file, it's a good point.

I suggest you to put the english text immediatly in your script and other languages in a separater .intl.min.js file f.i. so, english speaking people will ony link one .js

At this time, I've just copy/paste your translations (fr and us) in my own js and it's working.

Note : If I type the following code, there is a javascript fatal error 

```javascript
$("#myTimeline").albeTimeline(data, {
    language: "xx-XX"
});
```
because that language is invalid.  The best deal would first to check the existence of that language in your languages array and, as fallback, use the international english text to avoid error.

(the language can be set by the user who don't know if the plugin supported that locale)

**Comment by Albejr** [comment]
Fixed bug in v.2.0.1
Thanks for your contribution.
