### ISSUE TITLE
fnDateFormat output

### ISSUE THREAD

**Issue by zhangm3** [Albejr/jquery-albe-timeline#7]
In function fnDateFormat, line 154, why parts[1] -1? The output seems always one month less than the input. Thanks a lot!

**Comment by Albejr** [comment]
Let's see...
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

new Date(year, month, day, hours, minutes, seconds, milliseconds)
"month: Integer value representing the month, beginning with 0 for January to 11 for December."

Example...
Your date is: "September 11, 2001"
Javascript date: new Date(2001, 08, 11)

**Comment by zhangm3** [comment]
That is correct but the output is just trying to format the string of input date. Use your example,
Your date is: "September 11, 2001"
Javascript date: var newDate = new Date(2001, 08, 11)
I want the output as 9/11/2001.
d= newDate.getDate() => 11;
m=newDate.getMonth=>8;
y=newDate.getFullYear();
The output will be m + '/ '+ d + '/' + y =>8/11/2001 which is not what you want.
Hope it makes sense.
I apprediate your great work on this project.
Thanks again!

**Comment by Albejr** [comment]
I preferred not to create a dependency with another date formatting plugin (eg: "moment.js")

Check version 2.1.2
I added the return format, 5.:"MM/dd/yyyy "

**Comment by zhangm3** [comment]
Thanks Albejr.

**Comment by Albejr** [comment]
Check version 3.0.0
Pass the date format directly, instead of the enumerator.

```
$('#myTimeline').albeTimeline(data, {
        formatDate: 'MM/dd/yyyy'
});
```
